//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstDemo
{
    using System;
    
    [Flags]
    public enum CustomerType : byte
    {
        Lieferant = 0,
        Kunde = 1
    }
}
