// <auto-generated />
namespace VidApp.Migrations {
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTags : IMigrationMetadata {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTags));

        string IMigrationMetadata.Id {
            get { return "201710110433495_AddTags"; }
        }

        string IMigrationMetadata.Source {
            get { return null; }
        }

        string IMigrationMetadata.Target {
            get { return Resources.GetString("Target"); }
        }
    }
}
