// <auto-generated />
namespace VidApp.Migrations {
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddClassificationToVideosTable : IMigrationMetadata {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClassificationToVideosTable));

        string IMigrationMetadata.Id {
            get { return "201710110321392_AddClassificationToVideosTable"; }
        }

        string IMigrationMetadata.Source {
            get { return null; }
        }

        string IMigrationMetadata.Target {
            get { return Resources.GetString("Target"); }
        }
    }
}
